language: android
android:
  components:
    - build-tools-20.0.0
    - android-L

#language: java
#jdk:
#  - oraclejdk7
#  - openjdk7

before_install:
 - chmod +x gradlew

branches:
  only:
    - develop-studio

script:
  - TERM=dumb ./gradlew assembleDebug